[env]
_.python.venv = { path = "{{ config_root }}/.venv", create = true }
ANSIBLE_HOME = "{{ config_root }}/.ansible"

[hooks]
postinstall = "pip install -r {{ config_root }}/requirements.txt"

[tools]
actionlint = "1.7.7"
butane = "0.23.0"
python = "3.13.3"
typos-cli = "1.31.1"
zizmor = "1.5.2"

[alias]
butane = "asdf:Okeanos/asdf-butane"
typos-cli = "asdf:vic1707/asdf-any-cargo-quickinstall"
zizmor = "asdf:vic1707/asdf-any-cargo-quickinstall"

[settings]
experimental = true ## Enables hooks

[settings.python]
compile = false ## Forces download of precompiled bin
